version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      versioning-strategy: increase
      groups:
          minor-and-patch:
              update-types:
                  - 'minor'
                  - 'patch'
      ignore:
          - dependency-name: 'eslint'
            update-types: ['version-update:semver-major']
          - dependency-name: 'typescript'
            update-types: ['version-update:semver-major']
          - dependency-name: 'jsdom'
            update-types: ['version-update:semver-major']
          - dependency-name: '@types/node'
            update-types: ['version-update:semver-major']

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          minor-and-patch:
              update-types:
                  - 'minor'
                  - 'patch'
